### ISSUE TITLE
lodash missing from package.json dependencies

### ISSUE THREAD

**Issue by on-ye** [fieldbook/fieldbook-client#2]
When using the command **npm i fieldbook-client --save** lodash isn't installed as it's specified in devDependencies rather that dependencies in the package.json

> > Error: Cannot find module 'lodash'

**Comment by jasoncrawford** [comment]
Thanks for the report. Just put in a fix, will get someone to review/confirm/merge. In the meantime I think you can fix this just by doing an `npm install lodash` yourself at the top level.

**Comment by jasoncrawford** [comment]
Should be fixed by #3

**Comment by benbernard** [comment]
Just published 1.0.6 with this fix.  Thanks for the report!
